config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  namespace :admin do
    resources :employees
  end
  get 'home/index'
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  namespace :admin do
    resources :dashboard
    resources :departments
  end
  root 'home#index'
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
  validates :name, presence: true
end

app/models/employee.rb
class Employee < ApplicationRecord
  validates :name, presence: true
  belongs_to :department
  has_one_attached :image
end

app/models/mystery_partner.rb
class MysteryPartner < ApplicationRecord

  scope :with_year_and_month, ->(year, month) {
    where("date_part('year', created_at) = ? AND date_part('month', created_at) = ?", year, month)
  }

  scope :filter_by_department, -> (department_id) { where "employee1_department_id = ? or employee2_department_id = ?", department_id, department_id }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/base_controller.rb
module Admin
  class BaseController < ApplicationController
    # check_authorization unless: :devise_controller?

    before_action :authenticate_user!

    before_action :configure_permitted_parameters, if: :devise_controller?

    before_action :check_if_admin

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) do |user_params|
        user_params.permit(:email, :password, :password_confirmation, :admin)
      end
    end

    private

    def check_if_admin
      redirect_to root_path unless current_user.admin?
    end
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController
  layout 'admin/base'

  def index; end
end

app/controllers/admin/departments_controller.rb
module Admin
  class Admin::DepartmentsController < Admin::BaseController
    before_action :set_admin_department, only: [:show, :edit, :update, :destroy]

    # GET /admin/departments
    def index
      @admin_departments = Department.all
    end

    # GET /admin/departments/1
    def show
    end

    # GET /admin/departments/new
    def new
      @admin_department = Department.new
    end

    # GET /admin/departments/1/edit
    def edit
    end

    # POST /admin/departments
    def create
      @admin_department = Department.new(admin_department_params)
      if @admin_department.save
        redirect_to admin_department_url(@admin_department), notice: 'Department was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /admin/departments/1
    def update
      if @admin_department.update(admin_department_params)
        redirect_to admin_department_url(@admin_department), notice: 'Department was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /admin/departments/1
    def destroy
      @admin_department.destroy
      redirect_to admin_departments_url, notice: 'Department was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_admin_department
        @admin_department = Department.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def admin_department_params
        params.fetch(:department, {}).permit(:name)
      end
  end
end

app/controllers/admin/employees_controller.rb
module Admin
  class EmployeesController < Admin::BaseController
    before_action :set_admin_employee, only: [:show, :edit, :update, :destroy]

    # GET /admin/employees
    def index
      @admin_employees = Employee.all
    end

    # GET /admin/employees/1
    def show
    end

    # GET /admin/employees/new
    def new
      @admin_employee = Employee.new
    end

    # GET /admin/employees/1/edit
    def edit
    end

    # POST /admin/employees
    def create
      @admin_employee = Employee.new(admin_employee_params)

      if @admin_employee.save
        add_new_employee_existing_mystery_lunch
        redirect_to admin_employee_url(@admin_employee), notice: 'Employee was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /admin/employees/1
    def update
      if @admin_employee.update(admin_employee_params)
        redirect_to admin_employee_url(@admin_employee), notice: 'Employee was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /admin/employees/1
    def destroy
      @admin_employee.destroy
      remove_employee_from_coming_mystery_lunch
      redirect_to admin_employees_url, notice: 'Employee was successfully destroyed.'
    end

    private

    def set_admin_employee
      @admin_employee = Employee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def admin_employee_params
      params.fetch(:employee, {}).permit(:name, :department_id, :image)
    end

    def add_new_employee_existing_mystery_lunch
      if MysteryPartner.count > 0
        MysteryMatchModifier.new(employee_id: @admin_employee.id, department_id: @admin_employee.id, action: 'add').call
      end
    end

    def remove_employee_from_coming_mystery_lunch
      if MysteryPartner.count > 0
        MysteryMatchModifier.new(employee_id: @admin_employee.id, department_id: @admin_employee.id, action: 'delete').call
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # check_authorization unless: :devise_controller?

  # before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:email, :password, :password_confirmation, :admin)
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @mystery_partners = retrieve_mystery_lunch_partners
    render 'index.json.jbuilder'
  end

  private

  def retrieve_mystery_lunch_partners
    MysteryMatchRetrieval.new(department_id: params[:department_id], year: params[:year], month: params[:month]).call
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/dashboard/index.html.erb
<h1>Hello, welcome to admin section</h1>

app/views/admin/departments/_form.html.erb
<div class="container">
  <%= simple_form_for([:admin, @admin_department]) do |f| %>
      <div class="form-group">
        <%= f.input :name, label: "Department Name", input_html: { class: "form-control" } %>
      </div>

      <%= f.button :submit, "Create Employee", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/admin/departments/edit.html.erb
<h1>Editing Admin Department</h1>

<%= render 'form', admin_department: @admin_department %>

<%= link_to 'Show', admin_department_url(@admin_department) %> |
<%= link_to 'Back', admin_departments_path %>

app/views/admin/departments/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Admin Departments</h1>

  <table class="table">
    <thead>
      <tr>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @admin_departments.each do |admin_department| %>
        <tr>
          <td><%= admin_department.name %></td>
          <td><%= link_to 'Edit', edit_admin_department_path(admin_department) %></td>
          <td>
          <%= simple_form_for([:admin, admin_department], method: :delete) do |f| %>
              <%= f.button :submit, "Delete Department", class: "btn btn-primary" %>
          <% end %>
          <td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Admin Department', new_admin_department_path, class: "btn btn-primary" %>
</div>

app/views/admin/departments/new.html.erb
<div class="container">
<h1>New Department</h1>

<%= render 'form', admin_department: @admin_department %>

<%= link_to 'Back', admin_departments_path %>
</div>

app/views/admin/departments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_department_path(@admin_department) %> |
<%= link_to 'Back', admin_departments_path %>

app/views/admin/employees/_form.html.erb
<div class="container">
  <%= simple_form_for([:admin, @admin_employee]) do |f| %>
      <div class="form-group">
        <%= f.input :name, label: "Employee Name", input_html: { class: "form-control" } %>
      </div>
      <div class="form-group">
        <%= f.label :department_id, "Department" %>
        <%= f.collection_select :department_id, Department.all, :id, :name, { include_blank: true }, {class: "form-control"} %>
      </div>
      <div class="form-group">
        <%= f.input :image, as: :file, label: "Image upload", input_html: { class: "form-control-file" } %>
      </div>

      <%= f.button :submit, "Create Employee", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/admin/employees/edit.html.erb
<h1>Editing Admin Employee</h1>

<%= render 'form', admin_employee: @admin_employee %>

<%= link_to 'Show', admin_employee_url(@admin_employee) %> |
<%= link_to 'Back', admin_employees_path %>

app/views/admin/employees/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Admin Employees</h1>

  <table class="table">
    <thead>
      <tr>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @admin_employees.each do |admin_employee| %>
        <tr>
          <td><%= admin_employee.name %></td>
          <td><%= admin_employee.department.name %></td>
          <% if admin_employee.image.persisted? %>
              <td><%= image_tag(url_for(admin_employee.image.variant(resize: '100x100'))) %></td>
          <% end %>
          <td><%= link_to 'Edit', edit_admin_employee_path(admin_employee) %></td>
          <td>
            <%= simple_form_for([:admin, admin_employee], method: :delete) do |f| %>
                <%= f.button :submit, "Delete Employee", class: "btn btn-primary" %>
            <% end %>
          <td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>

  <%= link_to 'New Admin Employee', new_admin_employee_path, class: "btn btn-primary" %>
</div>

app/views/admin/employees/new.html.erb
<div class="container">
  <h1>New Employee</h1>

  <%= render 'form', admin_employee: @admin_employee %>

  <%= link_to 'Back', admin_employees_path %>
</div>

app/views/admin/employees/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_employee_path(@admin_employee) %> |
<%= link_to 'Back', admin_employees_path %>

app/views/home/index.html.erb
<div class="container">
  <div class="container">
    <div class="row spacer"></div>
    <div class="row">
      <div class="col-md-6">
        <h3>Mystery Lunch Partners for <%= @mystery_partners.present? ? @mystery_partners.last.created_at.strftime('%B , %Y ') : Time.now.strftime('%B , %Y ') %></h3>
      </div>
      <div class="col-md-6 text-right">
        <%= form_tag(root_path, method: :get) do %>
            <%= label_tag :year %>
            <%= select_tag :year, options_for_select((Time.now.year-5)..Time.now.year, params[:year]), include_blank: true %>

            <%= label_tag :month %>
            <%= select_tag :month, options_for_select(1..12, params[:month]), include_blank: true %>

            <%= label_tag :department %>
            <%= select_tag :department_id, options_for_select(Department.all.map { |d| [d.name, d.id] }, params[:department_id]), include_blank: true %>

            <%= submit_tag "Filter", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>

    <div class="row spacer"></div>

  <table class="table">
    <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
     <% @mystery_partners.each do |mystery_partner| %>
        <td style="display: none;"><%= employee1 = Employee.find(mystery_partner.employee1_id) %>
        <td style="display: none;"><%= employee2 = Employee.find(mystery_partner.employee2_id) %>
        <td style="display: none;"><%= employee3 = Employee.find_by(id: mystery_partner.employee3_id) %>
        <td style="display: none;"><%= profile_image = employee3.present? ? "profile-img3" : "profile-img" %>

        <tr>
          <div class="profile">
            <div class="profile1">

              <% if employee1.image.persisted? %>
                  <%= image_tag(url_for(employee1.image.variant(resize: '300x300')), :class => profile_image) %>
              <% end %>
              <div class="name">
                <%= employee1.name %>
              </div>
              <div class="department">
                <%= Department.find_by(id: employee1.department_id).name %>
              </div>

            </div>

            <div class="profile2">

              <% if employee2.image.persisted? %>
                  <%= image_tag(url_for(employee2.image.variant(resize: '300x300')), :class => profile_image) %>
              <% end %>
              <div class="name">
                <%= employee2.name %>
              </div>
              <div class="department">
                <%= Department.find_by(id: employee2.department_id).name %>
              </div>

            </div>

            <% if employee3.present? %>
              <div class="profile3">

                <% if employee3.image.persisted? %>
                    <%= image_tag(url_for(employee3.image.variant(resize: '300x300')), :class => profile_image) %>
                <% end %>
                <div class="name">
                  <%= employee3.name %>
                </div>
                <div class="department">
                  <%= Department.find_by(id: employee3.department_id).name %>
                </div>
              </div>
            <% end %>
          </div>
        </tr>
        <div class="row spacer"></div>
          <div class="row spacer"></div>
    <% end %>
    </tbody>
  </table>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="root_path">Mystery Lunch App</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to 'Home', root_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Departments', admin_departments_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Employees', admin_employees_path, class: 'nav-link' %>
          </li>
        </ul>
        <ul class="navbar-nav">
          <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link" %>
              </li>
          <% else %>
              <li class="nav-item">
                <%= link_to "Login", new_user_session_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to('Register', new_user_registration_path, class: "nav-link")  %>
              </li>
          <% end %>
        </ul>
      </div>
    </div>
</nav>

app/views/layouts/admin/base.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_tag 'application', media: 'all' %>
</head>

<body class='admin'>
<header>
  <%= render 'layouts/navigation' %>
</header>
<%= yield %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>

</head>

<body>
<header>
  <%= render 'layouts/navigation' %>
</header>
<%= yield %>
</body>
</html>